// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwj4KpPk3qH_M0VnxAsKczAQo0IU48_-k',
    appId: '1:699846551173:web:991400af1484c35da66bec',
    messagingSenderId: '699846551173',
    projectId: 'dosraghar',
    authDomain: 'dosraghar.firebaseapp.com',
    storageBucket: 'dosraghar.appspot.com',
    measurementId: 'G-4YVP3XPRPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsO6nh0qqCgyOI2kyFefsQvF2NhHf2HjM',
    appId: '1:699846551173:android:69cc4d9c67646e9ba66bec',
    messagingSenderId: '699846551173',
    projectId: 'dosraghar',
    storageBucket: 'dosraghar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvKbApr_VkvjZ09CKCeZkoD19lK6vrd0g',
    appId: '1:699846551173:ios:465d7d86f6c7d2d2a66bec',
    messagingSenderId: '699846551173',
    projectId: 'dosraghar',
    storageBucket: 'dosraghar.appspot.com',
    iosBundleId: 'com.example.dosraGhar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvKbApr_VkvjZ09CKCeZkoD19lK6vrd0g',
    appId: '1:699846551173:ios:9b5bd5e2073453aba66bec',
    messagingSenderId: '699846551173',
    projectId: 'dosraghar',
    storageBucket: 'dosraghar.appspot.com',
    iosBundleId: 'com.example.dosraGhar.RunnerTests',
  );
}
